### ISSUE TITLE
Не работают теги после клонирования расшаренной задачи

### ISSUE THREAD

**Issue by alikhil** [Codeforces/polygon-issue-tracking#100]
1. На аккаунте A создаем задачу, тегируем ее.
2. Раздаем доступ к этой задаче пользователю B
3. На аккаунте B клонируем эту задачу.
4. Пытаемся найти задачу по тегу.
5. ???? Не находим клонированную задачу(хотя если в глобальном списке задач мы найдем ее и откроем у нее будет присутствовать тег).

**Comment by FrolovAlex** [comment]
Fixed
