### ISSUE TITLE
Interactor is always treated as cpp.g++

### ISSUE THREAD

**Issue by Errichto** [Codeforces/polygon-issue-tracking#102]
I created an interactive problem. Everything (including invocations) works fine if I don't use c++11 in an interactor. After adding "vector<int> ww; for(int number : ww){}" to my interactor the system allows me to save (so in this moment it understands it's c++11) but later after running invocation I get FL with error:

Can't compile interactor File {name='inter.cpp', type='cpp.g++', content='Blob {sha1='7e3472d1463add045e2f8cb0fef8f5e0b13abadd', size=1679', compressionMethod=METHOD_NONE', data=length:1679,sha1:7e3472d1463add045e2f8cb0fef8f5e0b13abadd, content='#include...

Still, in "Files" I see that inter.cpp is marked as cpp.g++11. But, during the invocation the system think that it's cpp.g++ (note it in the error message above).

The problem name is ok-prime-100 (id 31314), in case someone needs this particular problem.

**Comment by FrolovAlex** [comment]
fixed
