### ISSUE TITLE
Do not add exta action "Delete" on problem conflict

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#106]
У меня нет под рукой задачи с конфликтом, но если появляется доп. действие "Delete", то это странно. Согласен, что так не должно быть и надо убрать.

**Comment by bimaoe** [comment]
Hi! I accidentally clicked on "Delete" when trying to solve a conflict and the problem was deleted. Is there any way of recovering it?

**Comment by FrolovAlex** [comment]
done
