### ISSUE TITLE
statements: allow \exmpfile for examples

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#107]
Currently, the example input and output are just pasted into the statement.
This leads to confusion when there are special characters in the input or output (see [this comment](http://codeforces.com/blog/entry/14184?#comment-307004) for an example).

An alternative way is to use `\exmpfile` from `olymp.sty`, like [here](https://github.com/GassaFM/olymp.sty/blob/master/problems/exampleproblem3/statement/exampleproblem3.en.tex).
The advantage is that all characters are processed verbatim: no `{-}{-}` or `\#` or `\symbol{95}` or `~` magic needed to process special characters.
The disadvantage is less flexible formatting: for example, long lines will just appear as they are in a PDF, no line breaks inserted.

It would be great if Polygon allowed using \exmpfile-style examples instead of the older paste-style.

**Comment by ruinshe** [comment]
ping for this issue, is there any plan to solve it?

Or do you have any workaround to support `#` in the sample output?

Currently, our output contain magic characters and it's generated by main solution (i.e. we add the sample input as test case 1, and it generate sample output automatically), and the output looks like:

```
Case #1: 123
Case #2: 345
```

Regards
