### ISSUE TITLE
Stress testing in interactive problems doesn't work at all

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#114]
First, main correct solution was in Java. Executing stress testing gives this: `com.codeforces.invoker.exception.OperationCrashedException: Can't generate answer for solution '%javaFileName%.jar8':  [verdict=OK, exitCode=11]`. In stress info it shows `Tests processed: 4`

When I change main correct to cpp solution and started stress testing again. It again shows `Tests processed: 4` every time and says that the stressed solution failed on the generated test with PE verdict. But it's wrong, after adding this test into testset the stressed solution passes it.

**Comment by FrolovAlex** [comment]
Implemented.
