### ISSUE TITLE
Removing the problem

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#115]
1. Create contest "contest"
2. Add problem "problem" and "problem2" to "contest" ("problem" is A and "problem2" is B)
3. Go to "problem" -> Advanced -> Delete
4. "contest" now consists of zero problems
5. Add new problem named "problem" to "contest" ("problem" is C)
6. Renumerate problems as ("problem" -> A, "problem2" -> B)
7. Empty alert and nothing is done :( It's sad...
8. Rename "problem" to "problem2"
9. Go to deleted problems, restore "problem"
10. Exclude problem "problem" from "contest"
11. Renumerate problems as ("new-problem" -> A, "problem2" -> B)
12. Rename "problem2" back to "problem"
    ![screenshot from 2016-09-06 18-33-03](https://cloud.githubusercontent.com/assets/3343858/18280564/28ed88ac-7462-11e6-8298-4e6382bebd53.png)
    ![screenshot from 2016-09-06 18-32-55](https://cloud.githubusercontent.com/assets/3343858/18280572/2d643f7a-7462-11e6-8ca3-04c2fe3cf069.png)

**Comment by FrolovAlex** [comment]
Fixed.
