### ISSUE TITLE
Web-editor of source files should not change line endings

### ISSUE THREAD

**Issue by dj3500** [Codeforces/polygon-issue-tracking#119]
Often, when I upload a file created offline, commit it, and then make changes to it online in the browser-editor on Polygon, it changes all the line endings (or adds spaces at the end of each line, or something like that). So, even though I made a simple change to one line in the file, the next diff in the email sent from Polygon looks like this:

![diff](https://cloud.githubusercontent.com/assets/437182/19629313/5aaa96ca-9972-11e6-8986-a074b4394cee.png)

which is a mess (and makes it hard to see the actual change).

**Comment by dj3500** [comment]
A different, maybe easier way to fix this would be to make the differ ignore \r\n <-> \n changes.

**Comment by FrolovAlex** [comment]
Fixed.
