### ISSUE TITLE
Manage access for all problems in contest.

### ISSUE THREAD

**Issue by zlobober** [Codeforces/polygon-issue-tracking#12]
![access](https://cloud.githubusercontent.com/assets/1856442/4926483/d5f9e332-6533-11e4-83cd-d9d045acf843.png)

It would be nice to have an option to grant access for certain user for all tasks in the contest, something like an additional dropdown list at the top of the column like shown on the picture (my design skills suck, I know)

**Comment by MikeMirzayanov** [comment]
Done.
