### ISSUE TITLE
Package contains checker, that doesn't exist

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#127]
Check.java selected as checker for the problem. Windows package contains problem.xml file with check.exe binary, but Linux package contains problem.xml file without any binary. This check.exe file even doesn't exist. Pictures contain difference between packages. I think, that Windows package shouldn't contain check.exe binary in problem.xml file.

![screenshot from 2016-12-14 19-36-57](https://cloud.githubusercontent.com/assets/3343858/21191018/e55a3394-c234-11e6-87cb-943dbe609163.png)
![screenshot from 2016-12-14 19-37-36](https://cloud.githubusercontent.com/assets/3343858/21191019/e573514e-c234-11e6-9057-d40880a4a752.png)

**Comment by FrolovAlex** [comment]
Can't reproduce it. Try to do it now and if you can reproduce this bug describe with more details.

**Comment by niyaznigmatullin** [comment]
problem id: 48329
