### ISSUE TITLE
Support shift+click in the list of tests

### ISSUE THREAD

**Issue by zlobober** [Codeforces/polygon-issue-tracking#134]
When changing group id for a large number of tests, it is very painful to choose all the tests using checkboxes. Good idea would be to support shift+click in the following way:

test 1
test 2 <- 1) click on this test
test 3
test 4
test 5 <- 2) shift+click on this test
test 6

As a result: tests 2-5 are chosen.

**Comment by FrolovAlex** [comment]
Implemented.
