### ISSUE TITLE
Add "group" field to the manual test creation page

### ISSUE THREAD

**Issue by zlobober** [Codeforces/polygon-issue-tracking#135]
It would be convenient to have it somewhere when adding a manual test. 

Also, when you create a manual test and save it, the creation page appears again; the group id should be the same as for the previous test (in order not to specify it again and again for each new test).

**Comment by MikeMirzayanov** [comment]
For sure it should be only if the checkbox "Enable groups" is checked for a testset.

**Comment by zlobober** [comment]
Of course.

**Comment by FrolovAlex** [comment]
Implemented.
