### ISSUE TITLE
Contests lists

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#140]
Make Contests page more organized. Make an ability to create Contest lists or something similar, so that the contests from the same competition or similar by any other reason are kept together. 

Now Contests page is very unorganized and it's not easy to find or see what contests you have.

**Comment by niyaznigmatullin** [comment]
For each contest list make it's own system of rights, so that contest lists can be shared to some group of people. On adding a new contest to this list, all of its problems are shared with corresponding rights to all the contributors of this contest list.

**Comment by MikeMirzayanov** [comment]
Contest groups have been introduced. Now only basic features are supported. Please, write the most valuable expected features as separate issues.
