### ISSUE TITLE
Copy feature for stresses (+ shared solutions)

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#141]
Должно быть так: для стресса есть ссылка Copy, по которой создается точная копия стресса, но список решений у них будет общим. Типа изменение набора решений в одном из них будет отражаться для другого и наоборот.

Реализовать навернео проще всего так, просто стрессу сделать еще поле solutionNamesUid и при копировании теста делать так: если такого поля еще нет (то есть оно null/empty), то присвоить его RandomUtil.randomToken, иначе оставить как есть (то есть в этом поле типа индивидуальный идентификатор списка решений). В созданной копии полностью всё скопировать, включая это поле.

То есть поддерживать инвариант: solutionNamesUid равны тогда и только тогда, когда solutionNames одинаковы и эти наборы решений суть один набор.

При редактировании stress-а надо смотреть, если есть solutionNamesUid , то пройтись по всем стрессам и если там такой-же solutionNamesUid, то обновить и там набор решений.

====

Реализацию следует разделить на две части: 1) просто тупо копирование 2) поддержка solutionNamesUid (то есть shared solution lists)

**Comment by FrolovAlex** [comment]
Implemented.
