### ISSUE TITLE
contest statement creation - error does not mention problem

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#144]
Suppose I create the PDF version of contest statements, and the creation fails for some reason: for example, checker or validator crashes or times out in one of the ~10 contest problems. The message goes like: `com.codeforces.polygon.statement.StatementProcessException: Unexpected verdict CRASHED: Validator 'validator.exe' returns exit code -1073741819`

I'd like to know in which problem the error happened.

**Comment by FrolovAlex** [comment]
Added problem name to information about fails.
