### ISSUE TITLE
make Polygon commit diff letters available online

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#145]
Currently, the most pleasant format to read the diffs is Polygon commit letters.
The diffs in the problems are not nearly as pretty (for starters, they diff whole lines instead of individual characters, and a single paragraph in a problem statement is often written in a single long line).

Unfortunately, many authors like to turn off messages when committing, and in this case, the pretty diff is not available anywhere at all.

Please make the letter version of diffs available in the Polygon interface as well.

**Comment by FrolovAlex** [comment]
Implemented change log on recent changes page.
