### ISSUE TITLE
TL main solution - unclear error messages

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#146]
Suppose that the author solution times out on a test.

When creating a package, the message is
`PackageException: Got exception while generating tests.`.

When previewing tests, the message is
`ERROR: Unexpected verdict TIME_LIMIT_EXCEEDED.`
in the column of input (not output), which adds to the confusion.
That leads to think that the generator times out, which is not the case.

I would like a message which mentions that the **main solution** timed out,
and the test number for the package generation message.

**Comment by FrolovAlex** [comment]
Fixed.
