### ISSUE TITLE
Wrong info when special case committing

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#149]
I had working copy for second revision. Then revision for problem changed to 4. I changed something to and committed changes without updating working copy. Well, I knew, that I wouldn't have any conflicts, because I know what my collaborator changed in the problem. I committed successfully, but Info cell on the problems or contest page is showing the information without my collaborator's changes. It shows second revision state + my current changes.

**Comment by FrolovAlex** [comment]
Fixed.
