### ISSUE TITLE
Exception while searching

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#150]
![screenshot from 2017-02-19 21-10-43](https://cloud.githubusercontent.com/assets/3343858/23104925/044ed768-f6e8-11e6-99c6-21b6f20e9079.png)

**Comment by FrolovAlex** [comment]
You can use "2^n" instead of 2^n. It seems ^ is a special character in a lucene syntax.

**Comment by niyaznigmatullin** [comment]
Oh, thanks. But still, it searches 2 and n separately. Is there any method to search it as an exact entry, without breaking to words?

**Comment by FrolovAlex** [comment]
Seems that it is impossible now.
