### ISSUE TITLE
Support custom CC address to send Polygon problem changes

### ISSUE THREAD

**Issue by zlobober** [Codeforces/polygon-issue-tracking#153]
It would be great to add an option for specifying an additional CC e-mail address to send the changes (like, when the contest is prepared by some company, an internal company mailing list).

This should be done both for a single problem and for the whole contest.

**Comment by FrolovAlex** [comment]
Do you mean special field for problem/contest with email. And commiting a problem if no "Don't send email notification" used also send to the specified emails?

**Comment by zlobober** [comment]
Yes, exactly.

**Comment by FrolovAlex** [comment]
Implemented.
