### ISSUE TITLE
Verifying custom output for statements even if test not used in statement

### ISSUE THREAD

**Issue by dj3500** [Codeforces/polygon-issue-tracking#160]
If a test has useInStatements:false, but it used to be true and a custom outputForStatement was added at that time, then currently we have:

useInStatements:false
outputForStatement:nonempty
verifyInputOutputForStatements:true

and this causes Polygon's verification mechanism to verify that output, giving some pretty cryptic error if it doesn't check out.

To fix: either erase inputForStatement and outputForStatement when useInStatements is made false, or check in the verification phase whether useInStatements is true (and not just verifyInputOutputForStatements).

**Comment by FrolovAlex** [comment]
Fixed.
