### ISSUE TITLE
statements/<language>/doall.sh in contest package

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#169]
There is a piece of code in `statements/[language]/doall.sh`:
```
for file in ./*.mp
do
    mpost $file
done
```

It doesn't work if there is no `*.mp` file. So please make it this:
```
for file in ./*.mp
do
    [ -e $file ] && mpost $file
done
```

When there are no `*.mp` files `$file` value is iterated over `[ "./*.mp" ]` list and calling `mpost ./*.mp` turns out to be `no "*.mp" file found`.

**Comment by FrolovAlex** [comment]
fixed
