### ISSUE TITLE
On contests page (frame) add information about contest creator and number of problems

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#170]
Колонку Action сделать уже. Добавить второй колонкой автора контеста. Количество задач написать под названием мелким серым.

**Comment by MikeMirzayanov** [comment]
Может вообще подписать с названиями задач.  Типа

problems (5): fast-cooking, color-t-shirts, build-fountains.

Возможно, надо отображать первые 8 задач, потом многоточие если больше.

**Comment by FrolovAlex** [comment]
implemented
