### ISSUE TITLE
Не слать письмо пользователям, которых удаляют из задачи

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#174]
Несколько раз был такой кейс:
1. Задача создана несколько лет назад, все о ней забыли
2. Автор удаляет всех остальных юзеров и использует задачу где-нибудь

Сейчас почему-то шлется письмо "эй, чувак, тут у тебя только что WRITE права отобрали в такой-то задаче".

**Comment by niyaznigmatullin** [comment]
Я не понимаю, почему не слать. Если я хочу владеть задачей, но у меня отбирают права, я хочу знать, кто это сделал.

Еще я не понимаю, в чем смысл удалять всех юзеров, чтобы поиспользовать задачу.

**Comment by FrolovAlex** [comment]
closed
