### ISSUE TITLE
Carriage returns \r are introduced into Attachment binary files before \n newlines

### ISSUE THREAD

**Issue by EvgeniSergeev** [Codeforces/polygon-issue-tracking#178]
When uploading files into Attachments, and then downloading them, they come back different (but not always). First, a PDF became corrupted this way, then the same thing with a GZipped file. As a minimal example, I uploaded a file with content exactly `'abc\n\r\nxyz\n'` (as a Python string), with filename `file.txt.gz`. Downloading it, I get back `'abc\r\n\r\nxyz\r\n'`. So, it would seem that `\r`s were inserted before `\n`s except where there were already `\r`s.

However, testing on another file, called `test_pdf.pdf.gz`, the file came back identical to the original, even though it contained `...\xbd|\n\x85...` among other things. So, an `\r` wasn't inserted. Why that happened this time, but not the other time: not sure.

Another clue is that the "Length" of attachments displayed in the table is correct. So the introduction of `\r`s seems to happen when downloading the files.

I haven't looked into the problem deeper than this, but from past experience, this could be a problem with how MIME type is declared in the HTTP response. ("application/x-binary" comes to mind.) Something else that suggests this is that when clicking the "Download" link for the file in the Attachments table, the browser sometimes, but not always, opens the file in a new tab as gibberish, rather than offering the usual "Save As..." download dialog.

**Comment by EvgeniSergeev** [comment]
Also, the files are fine when downloaded as part of a package.

**Comment by FrolovAlex** [comment]
fixed
