### ISSUE TITLE
Separate statement files for each part

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#183]
Currently, web-interface has several parts of statements as well as API (legend, input, output, notes, tutorial). It would be better to put these separate files to package separately, so that formats are compatible.

**Comment by MikeMirzayanov** [comment]
Надо в папках вида \statements\язык (в пакете), например в \statements\russian сделать подпапку model и положить туда файлики  (некоторые могут отсутствовать)

problem.legend.tex
problem.input.tex
problem.output.tex
problem.interaction.tex
problem.scoring.tex
problem.samples.%02d
problem.samples.%02d.a
problem.notes.tex

**Comment by MikeMirzayanov** [comment]
Потом решим с точным неймингом и надо ли в problem.xml это выносить.

**Comment by FrolovAlex** [comment]
implemented
