### ISSUE TITLE
Multiple test generators are not working.

### ISSUE THREAD

**Issue by Kostroma** [Codeforces/polygon-issue-tracking#19]
When creating a script containing multiple test generator, tests generated by it are empty.

**Comment by MikeMirzayanov** [comment]
Please, provide more information. What is exact content of generator?  What
is script line?

**Comment by Kostroma** [comment]
Generator makes a number of tests using function startTest. Script line is, for example, "gen > {15-28}" (this causes error "test 15 coincides with test 16") or "gen > 15" (this makes an empty test). Furthermore, it is impossible to save the same script in problems which were already used: when pushing the button "save script" without changing anything, the error "test n coincides with test (n+1)" occurs.

**Comment by MikeMirzayanov** [comment]
Can't reproduce it. Is it still actual?

**Comment by Kostroma** [comment]
It is OK now. Seems that some of your developers has fixed this, quite a
long time ago.
16 марта 2015 г. 11:51 пользователь "Mike Mirzayanov" <
notifications@github.com> написал:
