### ISSUE TITLE
Запуск решения на тест чекера не well-formed задачи

### ISSUE THREAD

**Issue by webreh** [Codeforces/polygon-issue-tracking#2]
Для задачи с отключенной Well-formed при попытке сгенерировать ответ на тест кнопкой "generate answer" получается ошибка валидатора. 

Например, создать задачу, снять well-formed, выставить чекер std::hcmp, валидатор с основной частью кода
inf.readInteger();
inf.readEoln();
inf.readEof();
и модельное решение с ключевой идеей
cout << 1;
После этого добавить тест для чекера "1" с переводом строки в конце и попробовать получить для него ответ кнопкой "generate answer" и увидеть "Generation failed. Reason: FAIL Expected EOLN (stdin) [validator validator.exe returns exit code 3]".

Вероятно, при запуске происходит trim перевода строки в конце.

**Comment by Fefer-Ivan** [comment]
Проблема исправлена. При следующем обновлении Polygon все будет работать.
