### ISSUE TITLE
Копирование сэмплов.

### ISSUE THREAD

**Issue by vovuh** [Codeforces/polygon-issue-tracking#203]
При копировании сэмпла левый бар, отвечающий за поднятие в самый верх страницы, мешает скопировать сэмпл полностью. На скриншоте видно, что этот бар практически полностью загораживает собой самый левый столбец сэмплов.
![samples](https://user-images.githubusercontent.com/8684895/31531623-2ff5462a-aff9-11e7-8672-adbd8847c4e2.png)

**Comment by FrolovAlex** [comment]
Fixed, will be in production soon.
