### ISSUE TITLE
To fix "HTTP Status 403" Apache errors

### ISSUE THREAD

**Issue by zlobober** [Codeforces/polygon-issue-tracking#21]
This errors happens:
1) after session expires (i. e. if you try to refresh the tab on the next day)
2) I think that it happens even more often, but I don't remember exact cases when I got this page

In this situation I usually open the polygon main page in a separate window and copy ccid from there, and everything works. This steps can be automated (or at least it is better to redirect user to login page).

**Comment by MikeMirzayanov** [comment]
Can you try to test that it is still actual (or not)?

**Comment by MikeMirzayanov** [comment]
N/A
