### ISSUE TITLE
Problems with test groups, validation result is cached for "preview tests"

### ISSUE THREAD

**Issue by glebshp** [Codeforces/polygon-issue-tracking#221]
Consider the following sequence of actions:
1. Create a new test.
2. Forget to mark it's test group.
3. Run "preview tests".
4. Default constraints are used, test fails validation.
5. Set valid group for this test.
6. Run "preview tests" again.
7. Test still fails validation. Validator output shows that group tag was not used.

I suppose this might be a caching issue, test group identifier not included in test hash.

**Comment by FrolovAlex** [comment]
fixed
