### ISSUE TITLE
Cannot create problem/statement

### ISSUE THREAD

**Issue by ftiasch** [Codeforces/polygon-issue-tracking#24]

**Comment by MikeMirzayanov** [comment]
We need more details.

**Comment by ftiasch** [comment]
For me (user @ftiasch on polygon.codeforces), I found myself cannot start editing a new problem, nor add new statement texts to the existed one (the svn panel said the status of problem.tex was UNKNOWN). However, I can still edit statement and commit (for statement created before today).

**Comment by MikeMirzayanov** [comment]
The reason seems to be fixed. Please, write me PM on Codeforces, I'll add problem.tex to your working copy manually.

**Comment by MikeMirzayanov** [comment]
Fixed
