### ISSUE TITLE
Summary для invokation

### ISSUE THREAD

**Issue by kunyavskiy** [Codeforces/polygon-issue-tracking#245]
Когда много решений и тестов, а еще и группы тяжело понять что именно произошло.
Хочется какой-то summary-view с основной инорфмацией вроде
1) количество каждого вердикта на каждой группе 
2) суммарный балл
3) максимальное время работы на каждой группе

**Comment by MikeMirzayanov** [comment]
Примерно такое уже есть.

**Comment by kunyavskiy** [comment]
Времени работы нет. То есть посмотреть какой запас у частичного решения на своей группе сейчас никак удобно нельзя.

**Comment by MikeMirzayanov** [comment]
Сделай, плз, отдельный четкий issue что хочется в этом вопросе.
