### ISSUE TITLE
"Groups points policy and dependencies" is broken. 

### ISSUE THREAD

**Issue by RezwanArefin01** [Codeforces/polygon-issue-tracking#247]
![ ](https://i.imgur.com/mATYYGl.png)  

I am seeing the "Groups points policy and dependencies" place like above. Though I added groups, it is not being shown there.

Another problem is, when I add points and click "Set points" it works fine, and reloads page. But when I set groups and click "Set groups", nothing happens, I needed to refresh page manually to see the group assigned. Also, when did with multiple test files, it sets group to only one test. :|

Aslo when I add test manually with "Add Test", if I assign Group then nothing happens after clicking "Create". But works with only points set. So basically nothings is working for groups. :| 

I am using Mozilla Firefox 60.0.2.

**Comment by MikeMirzayanov** [comment]
We've implemented a fix. Please, test it now.

**Comment by RezwanArefin01** [comment]
When there are no test cases, the form still looks the same. However after adding some tests it works as expected. :)
