### ISSUE TITLE
Tasks with subtasks is not supported

### ISSUE THREAD

**Issue by tncks0121** [Codeforces/polygon-issue-tracking#26]
It seems that, unfortunately, only ICPC-style tasks could be prepared properly. I think these features would be useful:
1. Giving information about subtasks in the validator, by arguments.
2. Adding "Subtasks" section in the description. It would be really nice if one can add a section they want.
3. Viewing scores at invocations, when "partically correct" is given from the checker.

**Comment by MikeMirzayanov** [comment]
Done
