### ISSUE TITLE
Incorrect tests in statement validation

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#27]
There are two samples in the problem, both have input/output-for-statements and no LaTeX. Verify checkbox is on. Can't create package  because of PackageException: Output for statements doesn't give OK while judging: statements/1.

Tried to compile validate/check them manually on local machine, it seems everything is OK.

**Comment by mgusarov** [comment]
Done.

**Comment by pmavrin** [comment]
I have the same problem, looks like it's not fixed yet.
