### ISSUE TITLE
Плохо работает с фигурными скобками в сэмплах

### ISSUE THREAD

**Issue by alex65536** [Codeforces/polygon-issue-tracking#271]
У меня сэмплы состояли из скобок: `{}()[]<>`. При попытке собрать условие я получаю

~~~~
Can't be rendered because of: Transformation failed: Too few arguments for exmp command.
~~~~

**Steps to reproduce**: добавить тест `}[]{][]()<>` в сэмплы.

**Comment by MikeMirzayanov** [comment]
Для этого есть input for statements, чтобы добавить тест в LaTeX-разметке.
