### ISSUE TITLE
Описания решений

### ISSUE THREAD

**Issue by izban** [Codeforces/polygon-issue-tracking#282]
Очень хочется иметь возможность написать какой-нибудь скрываемый description у решения. А то написал я _wa1, _wa2, _wa3, _wa4, _wa5, покрывающие какие-то случаи в задаче, и понять, что это вообще такое, невозможно. Есть вариант пытаться указывать это в названиях решений (_greedy, _naive, ???), но это ужасно. Есть вариант писать комментарии в названии решения, но, по-моему, это тоже сильно неудобно (и он не помогает найти нужное решение если ты видишь кучу _wa*). Я пытался для себя поддерживать какой-то файлик в Attachmens типа "solutions description", но не взлетело, слишком неудобно. 

Вариант решения — иметь возможность описать кратко решение (по типу Statement description в General info), но скрытое по умолчанию, чтобы не мусорить интерфейс.

**Comment by MikeMirzayanov** [comment]
У нас есть похожая штука notes для задачи. Надо чтобы выглядело похоже как эти notes (смотреть в список задач в контесте, по клику в название задачи можно добавить). А здесь должно выглядеть как-то так (и похоже на notes в задачах), в бэкенде тоже надо называть notes.

То есть Rename? заменяем на Rename, добавляем слева ссылку Notes. Сами их отображаем если  есть так же как у задач. При клику по Notes на месте notes появляется input, который можно сохранить по enter.

![image](https://user-images.githubusercontent.com/1701892/60332493-9c248680-999f-11e9-90ab-11587e3eeaa4.png)

**Comment by MikeMirzayanov** [comment]
Done
