### ISSUE TITLE
Problems with uploading checkers/validators

### ISSUE THREAD

**Issue by tncks0121** [Codeforces/polygon-issue-tracking#29]
1. Upload checker/validator at the page "/checker" or "/validator"
2. Delete the file at the page "files"
3. The removed file's name is still remaining at the right dashboard.

**Comment by MikeMirzayanov** [comment]
Can't reproduce it. Is it still actual?

**Comment by MikeMirzayanov** [comment]
I don't want to fix it. Some users use "delete/upload" pattern as a method to replace a checker.
