### ISSUE TITLE
Request for Linux/Windows/full package with API

### ISSUE THREAD

**Issue by ultmaster** [Codeforces/polygon-issue-tracking#296]
Is there a way to request for a full package with API? When I requested for a package built with "Full", all I got was a "Standard" package.

**Comment by dario2994** [comment]
I want to keep this request alive. This is duplicated of #411 and #410 .

This is crucial to use polygon when preparing problems for other online judges. If one uses polygon to prepare a regional contest, then having an API to download full packages eases the burden of having to manually generate and download full packages.
