### ISSUE TITLE
Подсветка синтаксиса плохо работает в validator review для чисел с разделителями

### ISSUE THREAD

**Issue by alex65536** [Codeforces/polygon-issue-tracking#301]
В C++14 появилась возможности писать разделители в числах, например:

```cpp
inf.readInt(1, 200'000, "n");
```

Но, если валидатор с таким числом просматривать в validator review, то весь остальной текст валидатора будет подсвечен зеленым, так как syntax highlighter думает, что все остальное - строка.

Please fix this.

**Comment by KalininN** [comment]
Duplicates #227 :(
