### ISSUE TITLE
"Run all stresses" button

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#302]
It is VERY annoying to click "Run" for each of 10+ stresses

**Comment by MikeMirzayanov** [comment]
Should be like this:

![image](https://user-images.githubusercontent.com/1701892/60258062-0cb69f00-98dd-11e9-8c4e-b21aa2a57afa.png)

"Run All Stresses" must appear if there is at least one stress. It should look like "Add Stress". It should run all non-running stresses.

**Comment by MikeMirzayanov** [comment]
Done
