### ISSUE TITLE
Add PyPy 2 and 3 to the languages list.

### ISSUE THREAD

**Issue by kcvajgf** [Codeforces/polygon-issue-tracking#305]
Python 2 and 3 is quite slow; it sometimes hits Polygon's CPU limits. PyPy is much faster, even for the same program. It sometimes reaches near C++ speeds.

For tasks with really slow generators, I would still fall back to C++/testlib, but for reasonably-sized problems, it would be nice to be able to use python (via pypy) for a bit more.

For simplicity, uploaded programs could still be autodetected as python 2 or 3, and pypy could be set explicitly if needed. (Although pypy default would also be okay.)

**Comment by MikeMirzayanov** [comment]
Done
