### ISSUE TITLE
Using pipes in generator script: add random argument to every command in line

### ISSUE THREAD

**Issue by YakutovDmitriy** [Codeforces/polygon-issue-tracking#307]
Sometimes tests for the problem are complex, e.g.:
- you have some data structure + queries
- you have several data structures

In such cases it is easy and logically to use pipes in generating script:
- `gen_graph 100 | gen_queries 200`

I've noticed that in such case random string is added only for the last command in pipe sequence, e.g. script above transforms into `gen_graph 100 | gen_queries 200 15d6b180750e2f7de059eb156286f151`. It means that all the graphs generated by this line are the same. It is not a big deal, you can just add argument by yourself: `gen_graph 100 asdfjhsakdjf | gen_queries 200`. But it is pretty uncomfortable use this in stresses.

I guess I won't be hard to add a random argument to every of commands in line

**Comment by MikeMirzayanov** [comment]
Is it about a stress?

**Comment by YakutovDmitriy** [comment]
> Is it about a stress?

No, this is about field "Script" on tab "Tests". But I guess this issue can be applied to stress tab too.

**Comment by MikeMirzayanov** [comment]
Fixed in stresses
