### ISSUE TITLE
Позволить отказаться от получения писем о коммитах

### ISSUE THREAD

**Issue by Um-nik** [Codeforces/polygon-issue-tracking#313]
Сейчас при коммите есть галочка "не посылать е-мэйл". Кажется, что решение о посылке е-мэйла должен принимать получатель. Если человек хочет следить за прогрессом в разработке задачи - пусть получает все е-мэйлы. Если не хочет - пусть не получает никакие.
Особенно меня раздражает эта ситуация в связи с прорешкой кф-раундов. Сейчас часто тестеров добавляют во все задачи в полигоне, после этого они получают пару сотен писем за несколько дней, хотя в разработке задач не участвуют.
Я считаю, что вместо галочки "не посылать е-мэйл" при коммите нужно сделать галочку "посылать мне е-мэйлы" у задачи (для обратной совместимости эта галочка по дефолту стоит).

**Comment by MikeMirzayanov** [comment]
Это не оно?

![image](https://user-images.githubusercontent.com/1701892/60512878-77514b80-9cde-11e9-96bb-712603a052ea.png)

**Comment by Um-nik** [comment]
Да, но кажется это недавно появилось :) Но я уже несколько раз воспользовался, спасибо.
Можно ещё в контест такую галку добавить, чтобы автоматически у всех задач этого контеста проставлялось?

**Comment by MikeMirzayanov** [comment]
И это тоже появилось.
