### ISSUE TITLE
Statements: Show warnings about wrong quotes

### ISSUE THREAD

**Issue by 300iq** [Codeforces/polygon-issue-tracking#320]
For example, it is not correct to use << in English, and often Russian problemsetters are using them after translating, so it would be great to have warnings about wrong usage of quotes.

**Comment by MikeMirzayanov** [comment]
Examples:

<pre>

Русский

Допустимо:
Он сказал <<привет>>, ответ равен <<\texttt{NO}>>\"--- решения не существует. Вывести `1' и `\t{e}'. Пришел Д'Артаньян и ущел Д'Артаньян.

Не допустимо (каждая строчка отдельный пример):
Он сказал "привет".
Он сказал ``NO'' и всё.
Он сказал ``123'' и всё.
Он сказал 'это провал'.

Английский:
Print ``hello''"--- welcome message. Pring ``\texttt{NO}'' or `0' or `\t{e}'. Test d'Artagnan and d'Artagnan.

Не допустимо (каждая строчка отдельный пример):
Print &lt;&lt;hello&gt;&gt;
Print "hello"
Print 'hello all' and exit
Print "\t{yes}"
Print \t{'yes'}

</pre>

**Comment by MikeMirzayanov** [comment]
Еще не допускать всякие UTF-8 кавычки, типа «такого»

**Comment by geranazavr555** [comment]
Например, 

“   U+201C LEFT DOUBLE QUOTATION MARK
”   U+201D RIGHT DOUBLE QUOTATION MARK

**Comment by MikeMirzayanov** [comment]
Готово
