### ISSUE TITLE
Cannot determine size of graphic in sample1.png (no BoundingBox)

### ISSUE THREAD

**Issue by cdkrot** [Codeforces/polygon-issue-tracking#321]
Меня часто огорчает проблема с тем что Latex полигона не может самостоятельно вычислить размер картинки.

>> Cannot determine size of graphic in sample1.png (no BoundingBox)

и нужно как-то извращаться с \includegraphics[bb=0 0 W H]{sample1.png}

При этом когда я локально собираю условие у меня никогда нет такой проблемы (texlive, linux, определение размера работает из коробки). Говорят что это решается установкой какого-то плагина latex. Нельзя ли это сделать?

**Comment by MikeMirzayanov** [comment]
Теперь может. Такое работает в новых задачах.
