### ISSUE TITLE
If a user deletes a solution, delete this solution from all stresses

### ISSUE THREAD

**Issue by arsijo** [Codeforces/polygon-issue-tracking#324]
I had such a problem:

1. Run a stress using a few solutions.

2. Deleted one of them in the "solutions" tab.

3. Run that stress again.

That stress will not work because one solution was deleted. There is no way to remove that solution from the stress list since that solution is not in the list anymore. Therefore, I need to delete that stress and create a new one.

I think the best solution is to remove the solution from all stresses after it was deleted.

**Comment by MikeMirzayanov** [comment]
Fixed. Also renaming is supported.
