### ISSUE TITLE
Customize Latex preamble for a single problem

### ISSUE THREAD

**Issue by dj3500** [Codeforces/polygon-issue-tracking#33]
Let's say you want to add something to the preamble to the latex document that gets compiled as the PDF statement for a single problem (like \usepackage{xcolor}). Now you can do this for an entire contest (by editing the file statements.ftl), but not for a single problem (there is a file problem.tex that one can edit, but it's not the entire latex document).

There is a workaround by making a contest with just this single problem, but this should be done easier.

**Comment by mgusarov** [comment]
Done.
