### ISSUE TITLE
Copy text from Data to Script line while adding test

### ISSUE THREAD

**Issue by cannor147** [Codeforces/polygon-issue-tracking#337]
If you want to change type of test, but you've already written test's content, this content will be lost:
![image](https://user-images.githubusercontent.com/32045407/60580948-a0c9b000-9d8e-11e9-80e1-440cfbf465dc.png)
![image](https://user-images.githubusercontent.com/32045407/60580962-aaebae80-9d8e-11e9-83c6-649fac84f892.png)

**Comment by cannor147** [comment]
Also test's content won't be lost totally. If you return type of test back, your content will be shown. But it's not obvious behavior.

**Comment by MikeMirzayanov** [comment]
Better: if a test has been added as script line, next test (after reload) should be also script line.
