### ISSUE TITLE
Ignore "__MACOSX"

### ISSUE THREAD

**Issue by arsijo** [Codeforces/polygon-issue-tracking#341]
Sometimes MAC users can get the message "Archive should contain only files, but __MACOSX is not a file" while attempting to upload a zip file. MAC creates a special folder in zip archive which are not visible for MAC users. It may confuse many people since not everybody knows about them. I think it would be useful to ignore such folders.

**Comment by geranazavr555** [comment]
It seems that the issue is fixed. Please, try out and confirm it.

**Comment by arsijo** [comment]
confirmed
