### ISSUE TITLE
Contest moves to the top of the list when problem revision changes

### ISSUE THREAD

**Issue by andrewzta** [Codeforces/polygon-issue-tracking#348]
When you change the revision of a problem in a contest, the contest moves to the beginning of the list. This makes old contests move to the top when problems from them are reused and changed.

Probably better behavior would be to move only if the contest itself is changed, or favorite, or make some other solution. 

Especially annoying in polygon.lksh.ru

![изображение](https://user-images.githubusercontent.com/516464/62029086-767edd00-b1ea-11e9-9c6b-346832b745e1.png)

**Comment by MikeMirzayanov** [comment]
Fixed
