### ISSUE TITLE
adding new solutions automatically

### ISSUE THREAD

**Issue by Stonefeang** [Codeforces/polygon-issue-tracking#349]
After making an invocation with all the tests, if we add some tests in the future and rejudge this invocation, the new tests will also be included. That's really great and helpful. Things are different if we consider solutions. If we add a new solution, we have to manually remove each invocation and add it back with a new subset of solutions. In my opinion, it would be nice if new solutions would be added automatically to the invocations which have the option "all solutions" marked.

**Comment by MikeMirzayanov** [comment]
Done
