### ISSUE TITLE
Add warning when using generators that produce more than one test case in a run

### ISSUE THREAD

**Issue by KalininN** [Codeforces/polygon-issue-tracking#353]

**Comment by cannor147** [comment]
What is the reason for warning these situations? Many people use multiple generators for generating tests of different kinds. I think, it's normal way to use more than one generators.

**Comment by KalininN** [comment]
I mean exactly the opposite (edited issue name). My point (and everyone I asked agree) that the `gen >{1-100}` syntax is much harder to support: you can't use them in stresses, you can't reorder tests, remove/add from web interface, you can't view parameters without looking into code.

**Comment by MikeMirzayanov** [comment]
Done
