### ISSUE TITLE
Binary files in emails

### ISSUE THREAD

**Issue by dj3500** [Codeforces/polygon-issue-tracking#36]
When binary files are added to a problem (to Attachments / auxiliaries), and this gets committed, everyone gets an email like

.....
ADDED files/auxiliaries/DOMJUDGECONTESTANT_examples_hard.zip
PK 3�kF�lȞ\G J ex2.in�]gv�8���s� ��7�>w+ T ���<�X""��l_��`��� ��� �}��F� o �~m b��N �D( ' (S�̋ ��� �ӳ� � �� _�� �y��� ��s� �Hbf �!�^�`��c�q G �B 
�<� ��D��Py�� Ɋv{H<?ˍ'뮎��b
�!,� ����_ �@ %�k1��� p�(IB�ڄ3s�"a���.� �� 2��N��ת ���
_�_kv� ��vp�.N�1 3'�z � q Ow�� A�B�}�#� !�j�� ;t���� �� 5�8Y� cE)�P%��� @�,�\�/�����f D��-.��� ���H�K �RƷ���Yh �E
...............

**Comment by kuviman** [comment]
Fixed. Will be released soon.
