### ISSUE TITLE
Adding problem to contest UI issue

### ISSUE THREAD

**Issue by kgeorgiy** [Codeforces/polygon-issue-tracking#362]
How to reproduce:
- Create a contest
- Create a problem
- Press `Add to Contest` link at the Problem page
- Enter the contest UID
- Press `Save` button
- Got Settings have been updated`

Expected behavior:
- The problem added to the contest
- The contest appeared at the `Contests` list at the Problem page

Actual behavior:
- Nothing happened

Expected behavior may be achieved via pressing `Enter` key at the `Contest UID` input, but there aren't any clues about that.

**Comment by MikeMirzayanov** [comment]
Fixed
