### ISSUE TITLE
Add possibility to copy checker tests

### ISSUE THREAD

**Issue by kgeorgiy** [Codeforces/polygon-issue-tracking#378]
Checker testing scenario:
- Generate "interesting" test input
- Use generated file as input in many checker tests (for each possibility of WA)

Currently, to make a small modification of the output (to get another WA) you have to:
- create test
- copy input via clipboard
- copy output via clipboard
- modify output
- generate answer

If it will be possible to copy checker test, these actions will be reduced to:
- copy test
- modify output

**Comment by MikeMirzayanov** [comment]
Done.
