### ISSUE TITLE
Add "View all contests" or some kind of live search on top of "Contests" page.

### ISSUE THREAD

**Issue by andrewzta** [Codeforces/polygon-issue-tracking#401]
![image](https://user-images.githubusercontent.com/516464/69742202-6dc4f600-114d-11ea-99e4-c0a13f033a9c.png)

**Comment by andrewzta** [comment]
It is a little bit inconvenient to scroll down each time

**Comment by MikeMirzayanov** [comment]
Added pagination on the top
