### ISSUE TITLE
Email from polygon not working

### ISSUE THREAD

**Issue by MiquelOrtega** [Codeforces/polygon-issue-tracking#408]
It is not sending confirmation emails to confimr email at registration. Codeforces email system is working properly (I can reset the password for instance)

**Comment by geranazavr555** [comment]
Could you explain your case? I can't reproduce the problem.

**Comment by joaquimortega** [comment]
The problem seems to be fixed now, but still I did not get confirmation email when I registered.
My username is mathusalen and I cannot login because I didn't get the confirmation email. I cannot register again because it says that the user is registered already but the email is not confirmed.

**Comment by geranazavr555** [comment]
Are you sure that you have no rules for filtering and sorting emails in your inbox? If it so, probably, the issue is in them.

**Comment by joaquimortega** [comment]
It could be the case. In any case, how can I ask again for confirmation of the email address? I cannot register with the same address because it says that the user already exists and  I cannot log in because the email address is not confirmed.

**Comment by MikeMirzayanov** [comment]
Can't reproduce.
