### ISSUE TITLE
Will polygon ever be open-sourced?

### ISSUE THREAD

**Issue by wil93** [Codeforces/polygon-issue-tracking#41]
Open sourcing polygon would mean, IMHO, boosting its development and increasing the set of features. Even if polygon required special configuration (maybe a lot of work to make all the compilers work correctly) it could easily be _dockerized_, so that one could just `docker pull` it and have it automatically configured. See [what is docker](https://www.docker.com/whatisdocker/) and [how to dockerize an application](http://docs.docker.com/userguide/dockerizing/).

Doing that could potentially bring these benefits:
- Improvements to the polygon web interface (if, among those who will contribute to polygon development, there will be people who are good at making web UIs).
- Improvements on the interoperability of polygon (towards this direction, some open-source projects are already starting to accept the "polygon" task format).

Also it would be awesome to be able to install private polygon instances, for many reasons:
- A private instance won't break even in the unfortunate case when the polygon servers aren't accessible.
- If there are strong requirements about not disclosing tasks data (statements, and so on), I guess that there could be issues on storing this data on polygon servers. However, if one can install its own polygon instance, then I think that _every_ national olympiad will set up its own instance and use it when preparing official tasks :smile:

**Comment by MikeMirzayanov** [comment]
No such plans
