### ISSUE TITLE
Diff shows extra trailing space at the end of every line

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#42]
1. Commit a file
2. Edit it in a textarea, save, commit again
3. Look at the diff. It shows extra space at the end of every line

**Comment by kuviman** [comment]
Can't reproduce. Can you check that it is still actual?

**Comment by alexeydergunov** [comment]
I get it. It happens if the original file has LF endings. After modification in a text area it's saved with CRLF endings. Picture: [http://savepic.su/5636521.png](http://savepic.su/5636521.png)

I think there are two options: 1) Remember line endings style for each file, 2) Convert all files to CRLF when they are uploaded

BTW, the character ¶ is annoying, maybe don't show it?

**Comment by MikeMirzayanov** [comment]
Can't reproduce. Probably, fixed.
