### ISSUE TITLE
Bug with preview

### ISSUE THREAD

**Issue by arsijo** [Codeforces/polygon-issue-tracking#422]
Как получить ошибку:

1. Пустой tutorial
2. Открываем preview условия
3. Дописываем что-то
4. Меняем вкладку на tutorial
<img width="1269" alt="Screen Shot 2020-03-23 at 16 19 08" src="https://user-images.githubusercontent.com/10142216/77326159-13fec200-6d22-11ea-94e6-3d1e7919feff.png">

**Comment by cannor147** [comment]
Fixed.
