### ISSUE TITLE
Incorrect warning about quotes in English statement

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#427]
Create a problem with the following legend:
```
``increase all elements in the segment $[l_j, r_j]$ by $v_j$''.
```
ER: no warnings
AR: warning: use quotes like `text' instead of ''. in section 'legend' of english statement

**Comment by MikeMirzayanov** [comment]
Can't reproduce it now. Probably, it is fixed now. Can you check it?

**Comment by alexeydergunov** [comment]
Now it is not shown inside a problem, but is shown on a contest page.
