### ISSUE TITLE
Support problems with arbitrary scores

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#428]
Ejudge allows to create marathon-like problems:
- score is a positive integer
- checker should always return WA and write the score to stdout

It would be great to see this functionality in Polygon and Codeforces.

Now there are partial scoring problems, but they are implemented via return code, it is suitable only for school problems with scores from 0 to 100.

**Comment by alexeydergunov** [comment]
Looks like you are able to prepare such problems: ICPC Challenge 2020 Warmup: https://codeforces.com/contest/1376/problem/B1

Any tutorial how to do it? And how to use these problems in mashups?

**Comment by MikeMirzayanov** [comment]
Just use void quitp(double points, const std::string &message = "") in a checker + IOI contest style

**Comment by alexeydergunov** [comment]
Also:
- you shouldn't output anything to cerr, it leads to 0 points always returned
- you can't set Text language in CF Gyms, but PHP works (it just redirects your "program" to stdout)
