### ISSUE TITLE
Don't give an error when trying to a add test that already exists

### ISSUE THREAD

**Issue by arsijo** [Codeforces/polygon-issue-tracking#433]
Sometimes I upload tests to polygon. If there is a test that already exists, polygon will give an error. However, IMHO, in 100% people will remove that duplicated test and continue uploading tests. Therefore, it does not make sense for me to give such error. I think it would be better to give a warning about that and continue uploading the rest of tests.

**Comment by KalininN** [comment]
This is indeed very annoying, especially when you work with some old problems, you just can't do anything.

**Comment by MikeMirzayanov** [comment]
Fixed, will be in production soon.
