### ISSUE TITLE
Review of a problem with picture has overlapping parts of text

### ISSUE THREAD

**Issue by adedalic** [Codeforces/polygon-issue-tracking#443]
When you add a picture to the problem legend a text in "Legend" and "Input" sections start to overlap.
When you add pictures in "Notes" section a text in "Notes" section starts to overlap with "Legend" section of the next problem in Contest Review mode.
The browser is Chromium-based Yandex browser.

The same problem occurs on clean Microsoft Edge (it's also Chromium-based, as far as I know). But on Edge it can be fixed with reloading page.

Since on my Ya.Browser reloads don't help, I can suggest that it's related to installed plugins. But as I see, the first load on Edge doesn't work as well, so I may suggest that the problem exists, but some kind of hack used as a workaround.

![image](https://user-images.githubusercontent.com/45667021/94523426-3aa63400-0242-11eb-95ea-d975e14a2902.png)

**Comment by MikeMirzayanov** [comment]
Is it reproducible now? Please, give us the problem-id to check.

**Comment by MikeMirzayanov** [comment]
> Is it reproducible now? Please, give us the problem-id to check.

?

**Comment by adedalic** [comment]
Looks like it's fixed now.
