### ISSUE TITLE
Java 8 - solution can't to be added from polygon to gym (codeforces)

### ISSUE THREAD

**Issue by e-r-** [Codeforces/polygon-issue-tracking#45]
In polygon:
1. Java8-specific solution (correct, not model solution) (in my case: used 'Hashmap' and its methods 'get()', 'put()', 'replace()', 'keySet()')
2. Package is created correctly (verification including)

In Codeforces:
0. Add gym
1. Put contest.xml into sandbox 
2. Update contest
Error: 
"Не удалось выпустить релиз соревнования из-за ошибок валидации:
On testset 'tests' SAS detected some errors in problem 'A': {{HAssortment.java, test 1: Can't produce output using solution 'HAssortment.java': Returns CRASHED [comment="Model solution returns with verdict OK and exit code 11", reason=INVALID_INPUT].}}."

Now: in polygon set Java7 instead Java8 (note! 'Check solution on compatibility' on Solution page - correct with java7 too...) for this solution, change type solution to 'incorrect', create package; in codeforces update contest, get accepted for java8-solution by send solution file in gym.

**Comment by MikeMirzayanov** [comment]
Fixed
