### ISSUE TITLE
Deleting tests from the middle of a testset is buggy

### ISSUE THREAD

**Issue by mraron** [Codeforces/polygon-issue-tracking#453]
I had some tests deleted from the middle of a testset and the tests coming after the deleted ones got their points and groups removed.
A reproduction of the issue:
![polygon_bug2](https://user-images.githubusercontent.com/1877241/102134387-b6357b80-3e56-11eb-9eab-8eb626200633.gif)

**Comment by MikeMirzayanov** [comment]
Fixed, will be in production in a day
