### ISSUE TITLE
Package creation with not committed changes

### ISSUE THREAD

**Issue by niyaznigmatullin** [Codeforces/polygon-issue-tracking#458]
1. Open Packages section of the problem (in Window 1)
2. Open another window (Window 2), and make some changes to the problem (in Window 2)
3. Click to create Full package (in Window 1)
The result is: the package is created, with the changes you made to working copy, but with the old revision number (that doesn't include the changes).

**Comment by MikeMirzayanov** [comment]
Can't reproduce
