### ISSUE TITLE
problem.viewTestGroup always returns code 400 saying there are no test groups

### ISSUE THREAD

**Issue by jvmusin** [Codeforces/polygon-issue-tracking#460]
The method problem.viewTestGroup always returns code 400 saying there are no test groups no matter if the problem has test groups enabled or not. The response body is:
```json
{
  "status": "FAILED",
  "comment": "testset: Test groups are disabled for the specified testset"
}
```
The problem (id 144845) for which I'm trying to get test groups has this testset:
![image](https://user-images.githubusercontent.com/9213880/109004137-c9b85a80-76c1-11eb-91d7-807ffb0d37e6.png)

**Comment by geranazavr555** [comment]
Will be fixed soon, thanks

**Comment by geranazavr555** [comment]
Seems to be fixed, check please

**Comment by jvmusin** [comment]
It works, thank you.
It would be great if you also update the TestGroup description in the documentation since it doesn't include the field named `feedbackPolicy`, but the response has this field.

**Comment by geranazavr555** [comment]
Done, @MikeMirzayanov

**Comment by jvmusin** [comment]
Thanks.

And I'd also report some inaccuracies according docs

There are two fields in the documentation of the `Test` entity:
`inputForStatements`
`outputForStatements`
But API returns this:
`inputForStatement`
`outputForStatement`
(without `s` at the and)

There is a field `revision` in the `Package` entity, but it's not decribed in the documentation.

**Comment by jvmusin** [comment]
Seems to be fixed, thank you.
