### ISSUE TITLE
Unchecking 'Are test points enabled?' toggler hides all the information about test groups

### ISSUE THREAD

**Issue by jvmusin** [Codeforces/polygon-issue-tracking#461]
If we have a problem with unchecked `Are test points enabled?` toggler on the `General info` page and checked `Enable groups` toggler on the `Tests` page, there is no table with information about test groups on the `Tests` page.

If we want to provide test group dependencies, we have to toggle  `Are test points enabled?` toggler to the `ON` state.

That's okay, I can't argue with this design decision, but the problem here is that when we call `problem.viewTestGroup` API method, it returns test groups together with the dependencies. I suppose, the dependencies should either be empty or excluded from the response when we have `Are test points enabled?` toggler in `OFF` state. Besides dependencies, `pointsPolicy` and `feedbackPolicy` should be excluded too.

The steps you need to make to reproduce this behaviour:
1. Create a problem with two test groups
2. Check  `Are test points enabled?` and `Enable groups` togglers
3. Depend the second test group on the first one
4. Disable the toggler `Are test points enabled?`
4a. Make sure there is no table with dependencies and other info about test groups on the `Tests` page
5. Call `problem.viewTestGroup` API method and see that there is a dependency you set at step 3

Another (and much better I suppose) solution would be to show the table about test groups whenever the `Enable groups` toggler is in `ON` state. The `Are test points enabled?` toggler should neither show nor hide the table. It should only add or remove the `Points` column and nothing more.

You can try it on the problem with id `159562`. I created it especially for this issue.

**Comment by jvmusin** [comment]
Long story short:
I want to see the table with test groups info iff the checkbox `Enable groups` is checked. Checking/unchecking `Are test points enabled?` should not affect the info appearance.

I'm actually talking about this table:
![image](https://user-images.githubusercontent.com/9213880/109826099-e7526a80-7c53-11eb-840a-6c145bb3d4cc.png)

**Comment by MikeMirzayanov** [comment]
Thanks, fixed.
