### ISSUE TITLE
full package does not build when file names are uppercase

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#464]
We had `GEN.CPP` and `VAL.CPP` in a problem.
Building a full package produced the following error:
`PackageException: Can't create or save package files: begin 0, end -1, length 7`
After we renamed them to lowercase, the issue vanished.
If that was indeed the issue, I would like a more clear error message.

**Comment by MikeMirzayanov** [comment]
Thanks, fixed. Also added cautions on files with uppercase letters in extensions.
