### ISSUE TITLE
Вывод чекера по-русски в invocations отображается в протоколе кракозябрами

### ISSUE THREAD

**Issue by dkirienko** [Codeforces/polygon-issue-tracking#469]
Задача output-only-sample-problem, id=180607

В этой задаче чекер на питоне  в UTF-8 и выводит русские сообщения. Они должны быть русскими, это нам нужно.

При запуске решения в Invocations вывод чекера (Comment) отображается в протоколе Run(s) details кракозябрами.

Если заменить кодировку чекера на CP1251, то результат будет точно такой же.

![photo_2021-08-25_17-05-06](https://user-images.githubusercontent.com/12986040/130805526-56784233-d6eb-4587-afd1-ebb46385a295.jpg)

**Comment by dkirienko** [comment]
Вот как выглядит вывод этого текста в HTML. Там написано "Даны верные ответы на 5 заданий из 5", это превращается в двубайтовую кодировку, где буква "Д" становится байтами 0xC3 0x84.

![изображение](https://user-images.githubusercontent.com/12986040/130807328-48a94dc4-e416-4523-ba5a-569509b892ff.png)

**Comment by MikeMirzayanov** [comment]
Просто используйте в чекере на Питоне такой сниппет:

~~~~~
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')
~~~~~
