### ISSUE TITLE
Visual C++ 2017

### ISSUE THREAD

**Issue by ivanovmp** [Codeforces/polygon-issue-tracking#481]
Please add Visual C++ 2017 to the Polygon. I clicked "Send package solutions" and now have some MS C++ solutions on the page https://codeforces.com/gym/103399/status, however this language is no more supported by Codeforces in the sense I cannoе filter MS C++ solutions out via Status filter.

**Comment by MikeMirzayanov** [comment]
Supported VS 2017 in Polygon
