### ISSUE TITLE
tutorial.ftl doesn't show in resource file

### ISSUE THREAD

**Issue by andrewzta** [Codeforces/polygon-issue-tracking#486]
tutorial.ftl doesn't show in resource file, but sometimes we need to edit it.

**Comment by MikeMirzayanov** [comment]
You can edit it in contest files. Do you really need to edit it for single problem?

**Comment by andrewzta** [comment]
Yes.

**Comment by andrewzta** [comment]
It sometimes takes long to render for the whole contest. Also sometimes some problems have broken tutorials. If I use something for particular problem (e.g. listings.sty), I cannot render tutorial.

**Comment by MikeMirzayanov** [comment]
Look into `tutorial.tex` file in resources. It will appear once you write a tutorial.
