### ISSUE TITLE
Отсутствует возможность добавить секцию Scoring к условию

### ISSUE THREAD

**Issue by dkirienko** [Codeforces/polygon-issue-tracking#496]
В некоторых задачах отсутствует галочка Show section 'Scoring' при вёрстке условия. Даже если создать новое условие, то добавить раздел Scoring к условию нельзя.

Предположительно, это проблема старых задач.
Примеры задач, в которых это наблюдается: 3052, 8778, 3286, 6008, 6196.
Это задачи, созданные в 2013 году и ранее.
При включении поддержки баллов в тестах всё равно галочка Scoring не появляется.

**Comment by MikeMirzayanov** [comment]
В самом деле, в очень старых задачах так. Исправить сложно. Не думаю, что есть необходимость.
