### ISSUE TITLE
ERROR: Unexpected verdict TIME_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by mynk322** [Codeforces/polygon-issue-tracking#497]
Working on my m1 mac air in less than 0.1 sec but giving ERROR: Unexpected verdict TIME_LIMIT_EXCEEDED in the output.
Verified in HackerEarth - its passing with 0.1 sec.
The time limit set is 15000ms.

**Comment by MikeMirzayanov** [comment]
Not enough information. Also, it is common for programs with undefined behavior to behave this way.
