### ISSUE TITLE
New field 'type' added to Package, but not to documentation

### ISSUE THREAD

**Issue by jvmusin** [Codeforces/polygon-issue-tracking#498]
Please, add information about `Problem.type` field to [the documentation](https://docs.google.com/document/d/1mb6CDWpbLQsi7F5UjAdwXdbCpyvSgWSXTJVHl52zZUQ/edit?ccid=8880487d88727f44ab2a911727d4d952#).

**Comment by geranazavr555** [comment]
Ready
