### ISSUE TITLE
Improve printing "…" in test preview

### ISSUE THREAD

**Issue by mikhail-dvorkin** [Codeforces/polygon-issue-tracking#510]
Suppose there is a test:

`4 5`
`#####`
`#####`
`#####`
`#####`

In the Tests tab, in the Content column its preview is:

`4 5`
`#####`
`#####`
`#####`
`#####...`

This "…" probably means that there is an end-of-line that did not fit into preview. But it is more confusing than helpful.

**Comment by MikeMirzayanov** [comment]
Fixed, it is OK now.
