### ISSUE TITLE
Proposal: use Unicode elipsis in tests preview

### ISSUE THREAD

**Issue by mikhail-dvorkin** [Codeforces/polygon-issue-tracking#511]
Considered a test with chessboard:
`4 6`
`#.#.#.`
`.#.#.#`
`#.#.#.`
`.#.#.#`

It will be previewed as:
`4 6`
`#.#.#.`
`.#.#.#`
`#.#.#.`
`.#....`

Which is confusing at the first sight. May I propose to change three dots "..." to single char: Unicode elipsis, "…" (U+2026). In most cases it will look strictly less confusing:

`4 6`
`#.#.#.`
`.#.#.#`
`#.#.#.`
`.#.…`

**Comment by MikeMirzayanov** [comment]
Done
