### ISSUE TITLE
Сделать ссылку на просмотр исходника чекера (как для стандартного, так и нет)

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#52]
По переходу можно просто показывать совсем пустую страницу с исходником (без подсветки и т.п.), просто отдать текст с content-type="text/plain". А можно и как html подсвеченный отдать.

Пример того, как должна выглядеть ссылка - в аттаче.
![checker](https://cloud.githubusercontent.com/assets/1701892/8203937/e73a0e32-14ed-11e5-804d-5c371f4ce865.png)

**Comment by FrolovAlex** [comment]
done
