### ISSUE TITLE
При использовании автоматического переводчика условий, вставка кода обрывается на знаках ==

### ISSUE THREAD

**Issue by dkirienko** [Codeforces/polygon-issue-tracking#521]
Имеется условие (я проверял на разборе, т.к. в разборе есть вставки программ). 
Где-то в тексте разбора встречаются знаки ==.
Запускаем автоматический перевод. Перевод осуществляется полностью. Однако, после вставки текста перевода в условие, текст обрывается на символах ==, которые вместе с последующим текстом не попадают в переведённое условие.
### Первый пример попытки перевода
![photo_2023-05-29_15-54-23](https://github.com/Codeforces/polygon-issue-tracking/assets/12986040/e78e4bbe-6947-4d84-9855-463684fcda9e)
![photo_2023-05-29_15-54-30](https://github.com/Codeforces/polygon-issue-tracking/assets/12986040/e2b1cfb3-3ad4-4b95-8d4c-2c25751af3a9)
### Второй пример попытки перевода
![photo_2023-05-29_15-54-37](https://github.com/Codeforces/polygon-issue-tracking/assets/12986040/a1f5a89e-846d-4e23-bace-c19169527e66)
![photo_2023-05-29_15-54-40](https://github.com/Codeforces/polygon-issue-tracking/assets/12986040/e790e48d-22df-4d8f-a3ea-b0a24653c14e)

**Comment by MikeMirzayanov** [comment]
Исправили
