### ISSUE TITLE
Generator flags with same name as the generator are not displayed properly

### ISSUE THREAD

**Issue by quangloc99** [Codeforces/polygon-issue-tracking#531]
![image](https://github.com/Codeforces/polygon-issue-tracking/assets/7441038/99f65353-19b5-4449-92b3-b21416464d93)

In this image, the second test generator script is shown as

```
gen -t 10000 -sum-n 200000 -min-n 10 -wr 1 -wp 1 -ws 1 -noise 0 --strat random
```

In reality, what I have typed is
```
gen -t 10000 -sum-n 200000 -min-n 10 -wr 1 -wp 1 -ws 1 -noise 0 -gen-strat random
```

Notice the last flag: `-gen-strat` was replaced with `--strat`.

This is only a visual bug, and does not affect the actual script. I guess the code was trying to replace the generator name with the display link?

**Comment by MikeMirzayanov** [comment]
Seems fixed now. Can you confirm?

**Comment by quangloc99** [comment]
Yes, I can confirm that this is fixed! Nice work!

I'll close this issue.
