### ISSUE TITLE
Cannot upload Python files to Polygon

### ISSUE THREAD

**Issue by gfmortega** [Codeforces/polygon-issue-tracking#535]
Attempting to upload a Python file to Polygon (anywhere---as a File, as a Solution, etc.) has been giving me a "Time out" page from CloudFlare, after a long period of stalling---and the upload does not push through.  This issue has occurred across several different problems.

PNGs as resource files of a statement have been uploaded successfully.  I haven't tested other file uploads

I can't pinpoint the exact time when this issue started, but I was able to upload Python files to Polygon at ~11am UTC of December 23, and not any more just a few hours after.  Might be coincidental, but there was a CF Round around that time

**Comment by MikeMirzayanov** [comment]
Can't reproduce now
