### ISSUE TITLE
Polygon -> Codeforces: no default compiler substitution

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#546]
When preparing a contest on Codeforces, there is a feature to automatically submit some author solutions from Polygon, or just every such solution.

Recently, C++20 appeared in Polygon. However, this feature does not work with C++20, apparently because C++20-on-Codeforces is some different flavor from C++20-in-Polygon. Such submissions fail with an error message "can not find compiler ... for solution ...".

What would help is some rules to automatically find the best fit from the available compilers, and use that.

**Comment by MikeMirzayanov** [comment]
Fixed
