### ISSUE TITLE
в столбце Info у задачи no solutions, когда на самом деле решения есть

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#55]
Добавляем в пустую задачу два решения: Correct и Incorrect, коммитим.
При этом как Main correct solution ни одно решение не отмечено, тестов 0.
После этого в списке задач в Info column написано **no solutions**.
Точнее было бы **no main solution** (2/1).
Задача https://polygon.codeforces.com/p/gassa/gassa-test-problem, Майку дал доступ.

**Comment by GassaFM** [comment]
Use case: я не автор, поэтому не хочу отмечать своё решение как Main, просто хочу добавить решений по имеющемуся на этот момент условию.

**Comment by MikeMirzayanov** [comment]
Fixed
