### ISSUE TITLE
Interactive problems: make it possible to use \Interaction instead of \InputFile and \OutputFile

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#57]
В интерактивных задачах бывает, что гораздо удобнее описывать протокол взаимодействия подряд (ввод и сразу вывод), чем отдельно весь ввод и отдельно весь вывод.

Бывает и наоборот: например, когда интерактивность заключается только в онлайновости, обычное описание (ввод и вывод отдельно) тоже часто подходит.

Сейчас мы сделали такое условие так:
1. В легенде написали:<br>
   ... (легенда)<br>
   \Interaction<br>
   ... (протокол взаимодействия)<br>
   Для этого нужен olymp.sty, в котором поддерживается \Interaction.
2. Оставили поля Input и Output пустыми и через freemarker template в Files/problem.tex добавили условие "скрывать их, если они пустые". Такое условие не помешает и остальным задачам, это можно поставить в problem.tex по умолчанию.

После этого pdf-ка собирается хорошо, но остаются следующие проблемы:
1. olymp.sty нужно самостоятельно перекачать, чтобы он поддерживал \Interaction. Я вставил tutorial в мастер-версию https://github.com/GassaFM/olymp.sty, можно попробовать взять её.
2. HTML-условие не собирается, потому что не знает про \Interaction. Это стоит исправить, в том числе если на CF планируются интерактивные задачи.
3. Хочется поддержки поля \Interaction вместо полей \InputFile и \OutputFile в интерфейсе Полигона. Можно в интерактивных задачах на странице с условиями добавить галочку, которая скрывает и показывает соответствующие текстовые поля. Так, как сейчас это сделано с примерами для условий.

**Comment by FrolovAlex** [comment]
Добавлена секция Interaction и ее поддержка для pdf и html условий
