### ISSUE TITLE
Решение с idleness limit on test 1 не валидируется ни как Incorrect, ни как Failed

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#59]
Решение получает idleness limit на первом тесте.

На самом деле решение было для предыдущей (не интерактивной) версии задачи.

Ставим ему тэг Incorrect или Failed - не помогает пройти валидацию.

В этом конкретном случае переложили решение в Attachments.

В целом - выглядит как баг, что никакой тэг не подходит. Возможно, есть use case, где класть такое решение в Attachments будет странно.

**Comment by FrolovAlex** [comment]
Теперь такое решение на первом тесте получит вердикт FL.
