### ISSUE TITLE
Решение с прорешивания на границе TL - непонятно, какой ставить тег

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#60]
В задаче есть авторские решения, среди которых OK отсекаются от TL.

После прорешивания добавляем в Полигон решение, которое упихано на границе TL (причём не на инвокерах Полигона, а на другой системе).

Непонятно, какой тег ставить такому решению: OK или Time Limit.
Оно ценно как решение в Полигоне, но не хочется валидировать, какой именно из тегов надо ставить.
Возможно, вердикт ещё и скачет от перетестирования, если оно действительно на границе.

Помог бы тэг типа Suboptimal для запихнутых решений.

Проблема: в задачах, в которых всё должно быть хорошо (не на жёсткую оптимизацию, без упихнутых не-авторских решений), нужно сделать так, чтобы этот тег не возникал соблазн ставить.

**Comment by FrolovAlex** [comment]
Добвален тег Time Limit or Accepted
