### ISSUE TITLE
Пожелание: кастомизация набора секций условия

### ISSUE THREAD

**Issue by kunyavskiy** [Codeforces/polygon-issue-tracking#74]
Возможность кастомизировать набор секций в условии приличным способом, а не хаками в .tex.

Пример:

1) В интерактивной задаче хочется иметь "Протокол взамодействия (\kw@Interation в olymp.sty)" вместо формата выходного файла. 
2) Во многих школьных задачах хочется иметь секцию Scoring

**Comment by zlobober** [comment]
Поддерживаю!

**Comment by FrolovAlex** [comment]
done
