### ISSUE TITLE
problem.tex - два добавления

### ISSUE THREAD

**Issue by GassaFM** [Codeforces/polygon-issue-tracking#83]
Можно сделать следующее в problem.tex задачи по умолчанию:

1.

<#if (problem.input??) && (problem.input?length > 0)>
\InputFile
${problem.input}

</#if>

<#if (problem.output??) && (problem.output?length > 0)>
\OutputFile
${problem.output}

</#if>

2.

<#if (problem.sampleTests?size > 0)>
<#if (problem.sampleTests?size > 1)>\Examples<#else>\Example</#if>

**Comment by FrolovAlex** [comment]
done
