### ISSUE TITLE
Тесты для валидатора не запускаются, если ввод/вывод в задаче не через stdin/stdout

### ISSUE THREAD

**Issue by KalininN** [Codeforces/polygon-issue-tracking#84]
Если ожидаемый вердикт VALID, то все падает с `java.io.IOException: Can't rename C:\Contesters\...\run\file.out to C:\Contesters\...\answer.fd0138e687.txt`
Если убрать файлы в задаче, то все ок.

**Comment by FrolovAlex** [comment]
fixed
