### ISSUE TITLE
Неинформативный текст ошибки

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#89]
Сегодня столкнулся с такой проблемой в Polygon при предварительном просмотре тестов:
[ERROR] Unexpected error has been found: null

Разобрался: я не указал название чекера. 

Тем не менее, пожелание системе быть более информативной, когда дело доходит до такой ошибки. Никаких следов, ведущих к не указанному чекеру не было. 

Как мне кажется, ситуация была такая: вначале был кастомный чекер checker.cpp, потом я его заменил на новый кастомный чекер с названием check.cpp. Поменял решения, они уже работали с файлами. И затем начал ловить NullPointerException'ы при любом прикосновении к тестам. Затем все, что я сделал, это изменил название чекера с checker.cpp (которого к тому времени уже не было в системе, я его удалил при загрузке нового) на check.cpp и все стало работать. 

Думаю, NullPointerException как-то связан с тем, что имя старого чекера сохранилось, при этом он уже отсутствовал в системе.

**Comment by FrolovAlex** [comment]
fixed
