### ISSUE TITLE
Неправильная обработка вердикта чекера в Preview Tests и Statement

### ISSUE THREAD

**Issue by dansagunov** [Codeforces/polygon-issue-tracking#90]
В Invocation и в Checker Tests чекер, как и должно быть, возвращает FAIL, но в Preview Tests и Statement тест отображается как корректный. Воспроизводится тестом 1 в задаче https://polygon.codeforces.com/p/dans/smallest-string-by-pfunc-copy.

**Comment by FrolovAlex** [comment]
fixed
