### ISSUE TITLE
Groups. New tests.

### ISSUE THREAD

**Issue by Burunduk1** [Codeforces/polygon-issue-tracking#96]
Добавляем новый тест в начало.
Группы съезжают, так как номер группы жёстко привязан к номеру теста. Приходится перепроставлять группы руками.

1) Можно привязывать группу к строке генерации.
2) Более просто при вставке теста в середину менять группы у суффикса тестов.

**Comment by FrolovAlex** [comment]
Ну вот не очень понятно: мы зачастую выделяем, например, группы по размеру теста или его специфике. Типа "small" для тестов с n<=100, "meduim" для тестов n<=1000. В таком случае логично же, что группа привязана к тесту. У вас какой-то другой паттерн использования?

**Comment by Burunduk1** [comment]
Как раз такой паттерн.
У нас почти все тесты генерятся автоматически. Съезжают номера групп для тестов, которые автоматически генерируются.

**Comment by MikeMirzayanov** [comment]
Сейчас стало сильно лучше. Проверьте, как работает. И переоткройте ишью с новым описанием, если что-то плохо.
