### ISSUE TITLE
Conflicts.

### ISSUE THREAD

**Issue by Burunduk1** [Codeforces/polygon-issue-tracking#97]
![image](https://cloud.githubusercontent.com/assets/8378085/14335441/9a97b3ee-fc5b-11e5-9a16-2dbe3817c8cb.png)

Конфликта нет. Update работает. Commit работает. В View Problems отображается кконфликт. Если щёлкнуть на resolve пишет "no conflict", конфликта больше нет.

**Comment by MikeMirzayanov** [comment]
Can't reproduce
