### ISSUE TITLE
Invokets. Testing.

### ISSUE THREAD

**Issue by Burunduk1** [Codeforces/polygon-issue-tracking#98]
Регулярная ситуация: 
1. Invokers waiting: от 50 до 120
2. Запускаю очередной invocation 2-10 решений, ничего не поменяв в тестах, в задаче вообще.
3. Не тестится несколько секунд, затем начинает меееедленно по 1-4 теста тестить (на всех работает мгновенно).

Сегодня в течение разработки ситуация воспроизводилась 25-50% запусков.

Забавный эффект: часто быстрее запустить новый invocation из под другого пользователя, чем ждать моего.

**Comment by MikeMirzayanov** [comment]
Уже не релевантно.
